django_project/amlit_helpdesk/urls.py
__author__ = 'Irwan Fathurrahman <meomancer@gmail.com>'
__date__ = '19/08/20'

from django.conf.urls import url
from django.urls import include

from amlit_helpdesk.api.ticket import (
    TicketListView,
    FeatureTicketListView,
    FeatureTicketFeatureDetailAPI)
from amlit_helpdesk.views.form_view import create_ticket

app_name = 'amlit_helpdesk'

api_url = [
    url(r'^tickets/$',
        view=TicketListView.as_view(),
        name='ticket-list'),
    url(r'^feature/(?P<id>\d+)/tickets/$',
        view=FeatureTicketListView.as_view(),
        name='feature-ticket-list'),
    url(r'^feature-ticket/(?P<id>\d+)/feature$',
        view=FeatureTicketFeatureDetailAPI.as_view(),
        name='feature-ticket-detail'),
]
urlpatterns = [
    url(r'^tickets/submit/$',
        create_ticket,
        name='submit'),
    url(r'^api/', include(api_url)),
]

django_project/core/urls.py
# coding=utf-8
"""Project level url handler."""
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

admin.autodiscover()

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^auth/', include('django.contrib.auth.urls')),
    url(r'^work-order/', include('amlit_helpdesk.urls')),
    url(r'^work-order/', include('amlit_helpdesk.urls_helpdesk')),
    url(r'^', include('civitas.urls')),
    url(r'^', include('amlit.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_project/amlit_helpdesk/forms/ticket.py
__author__ = 'Irwan Fathurrahman <meomancer@gmail.com>'
__date__ = '27/08/21'

from django import forms
from django.utils.translation import ugettext_lazy as _
from helpdesk.forms import TicketForm, CUSTOMFIELD_DATE_FORMAT, CUSTOMFIELD_DATETIME_FORMAT
from helpdesk.models import Ticket
from amlit_helpdesk.forms.recurring_type import RecurringTypeInput
from amlit_helpdesk.forms.widget.expected_time import ExpectedTimeInput

DEFAULT_PRIORITY = 3


class AmlitTicketForm(TicketForm):
    title = forms.CharField(
        max_length=100,
        required=True,
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        label=_('Summary of issue or task'),
    )

    body = forms.CharField(
        widget=forms.Textarea(attrs={'class': 'form-control'}),
        label=_('Description of issue or task'),
        required=True,
        help_text=_('Please be as descriptive as possible and include all details'),
    )
    queue = forms.ChoiceField(
        widget=forms.Select(attrs={'class': 'form-control'}),
        label=_('Type'),
        required=True,
        choices=()
    )
    priority = forms.ChoiceField(
        widget=forms.Select(attrs={'class': 'form-control'}),
        choices=Ticket.PRIORITY_CHOICES,
        required=True,
        initial=DEFAULT_PRIORITY,
        label=_('Priority'),
        help_text=f"Please select a priority. If unsure, leave it as '{Ticket.PRIORITY_CHOICES[DEFAULT_PRIORITY - 1][1]}'.",
    )
    start_date = forms.DateTimeField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'autocomplete': 'off'}),
        required=True,
        input_formats=[CUSTOMFIELD_DATE_FORMAT, CUSTOMFIELD_DATETIME_FORMAT, '%d/%m/%Y', '%m/%d/%Y', "%d.%m.%Y"],
        label=_('Start on'),
    )
    expected_time = forms.CharField(
        widget=ExpectedTimeInput(attrs={'class': 'form-control'}),
        required=False,
        label=_('Expected time to complete task'),
    )
    recurring_type = forms.CharField(
        required=False,
        widget=RecurringTypeInput(attrs={'class': 'form-control'}),
        label=_('Recurring ticket by'),
        help_text=_(
            'A new ticket with the same details as this one will be created on each recurrence.'),
    )
    attachment = forms.FileField(
        widget=forms.FileInput(attrs={'class': 'form-control-file'}),
        required=False,
        label=_('Attach File'),
        help_text=_('You can attach a file such as a document or photo to this ticket.'),
    )
    assigned_to = forms.ChoiceField(
        widget=(
            forms.Select(attrs={'class': 'form-control'})
        ),
        required=False,
        label=_('Assign to')
    )

    def __init__(self, *args, **kwargs):
        assigned_to_choices = None
        try:
            assigned_to_choices = kwargs.pop("assigned_to_choices")
        except KeyError:
            pass
        super(AmlitTicketForm, self).__init__(*args, **kwargs)
        self.fields['submitter_email'].widget = forms.HiddenInput()
        if assigned_to_choices:
            self.fields['assigned_to'].choices = [(0, '--------')] + [(u.id, u.get_username()) for u in assigned_to_choices]

        try:
            self.fields['queue'].initial = self.initial['queue']
        except KeyError:
            pass

django_project/web-app/templates/helpdesk/base.html
{% extends 'pages/base.html' %}
{% load i18n %}
{% load saved_queries %}
{% load load_helpdesk_settings %}
{% load static %}
{% with request|load_helpdesk_settings as helpdesk_settings %}
    {% with user|saved_queries as user_saved_queries_ %}

        {% block title %}
            Work Orders
        {% endblock %}

        {% block extra_stylesheet %}
            <link href="{% static 'css/helpdesk.css' %}" rel="stylesheet" type="text/css" media="screen, projection"/>
            <script type="text/javascript" src="{% static 'js/forms/widget/recurring_type.js' %}"></script>
            <script type="text/javascript" src="{% static 'js/forms/widget/expected_time.js' %}"></script>
        {% endblock extra_stylesheet %}

        {% block content %}
        {% endblock content %}

        {% block extrascripts %}
        {% endblock extrascripts %}

    {% endwith %}
{% endwith %}

django_project/web-app/templates/helpdesk/report_base.html
{% extends 'pages/base.html' %}
{% load i18n %}
{% load saved_queries %}
{% load load_helpdesk_settings %}
{% load static %}

{% block extra_stylesheet %}
    <link href="{% static 'css/helpdesk.css' %}" rel="stylesheet" type="text/css" media="screen, projection"/>
    <link href="{% static 'css/helpdesk-report.css' %}" rel="stylesheet" type="text/css" media="screen, projection"/>
    <link href="{% static 'helpdesk/vendor/morrisjs/morris.css' %}" rel="stylesheet">
    <link href="{% static 'helpdesk/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <script type="text/javascript" src="{% static 'js/forms/widget/recurring_type.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/forms/widget/expected_time.js' %}"></script>
{% endblock extra_stylesheet %}

{% block info %}
    <div class="row">
        <div class="col-sm-3">
            <ul id="sidebar">
                <li class="{% if not title %}active{% endif %}">
                    <a href="{% url "helpdesk:report_index" %}">{% trans "Reports & Statistics" %}</a>
                </li>
                <li class="title">
                    {% trans "Reports By User" %}
                </li>
                <li class="sub-title {% if title == 'User by Priority' %}active{% endif %}">
                    <a href="{% url "helpdesk:run_report" "userpriority" %}">{% trans "by Priority" %}</a>
                </li>
                <li class="sub-title {% if title == 'User by Queue' %}active{% endif %}">
                    <a href="{% url "helpdesk:run_report" "userqueue" %}">{% trans "by Queue" %}</a>
                </li>
                <li class="sub-title {% if title == 'User by Status' %}active{% endif %}">
                    <a href="{% url "helpdesk:run_report" "userstatus" %}">{% trans "by Status" %}</a>
                </li>
                <li class="sub-title {% if title == 'User by Month' %}active{% endif %}">
                    <a href="{% url "helpdesk:run_report" "usermonth" %}">{% trans "by Month" %}</a>
                </li>
                <li class="title">
                    {% trans "Reports By Queue" %}
                </li>
                <li class="sub-title {% if title == 'Queue by Priority' %}active{% endif %}">
                    <a href="{% url "helpdesk:run_report" "queuepriority" %}">{% trans "by Priority" %}</a>
                </li>
                <li class="sub-title {% if title == 'Queue by Status' %}active{% endif %}">
                    <a href="{% url "helpdesk:run_report" "queuestatus" %}">{% trans "by Status" %}</a>
                </li>
                <li class="sub-title {% if title == 'Queue by Month' %}active{% endif %}">
                    <a href="{% url "helpdesk:run_report" "queuemonth" %}">{% trans "by Month" %}</a>
                </li>
            </ul>
        </div>
        <div class="col-sm-9 content">
            <div id="content">
                {% block sidebar_content %}
                {% endblock sidebar_content %}
            </div>
        </div>
    </div>
{% endblock %}


{% block title %}
    {% trans "Reports & Statistics" %}
{% endblock %}

{% block header %}
    {% trans "Reports & Statistics" %}
{% endblock header %}

django_project/web-app/templates/helpdesk/report_index.html
{% extends "helpdesk/report_base.html" %}
{% load i18n %}
{% load static %}

{% block sidebar_content %}
    {% if number_tickets == 0 %}
        <p>{% trans "You haven't created any tickets yet, so you cannot run any reports." %}</p>
    {% else %}
        <table class="table table-striped table-bordered table-hover">
            <tbody>
            <tr>
                <td>
                    {% trans "Average number of days until ticket is closed (all tickets): " %}
                </td>
                <td>
                    <strong style="color: red;">{{ basic_ticket_stats.average_nbr_days_until_ticket_closed }}</strong>
                </td>
            </tr>
            <tr>
                <td>
                    {% trans "Average number of days until ticket is closed (tickets opened in last 60 days): " %}
                </td>
                <td>
                    <strong style="color: red;">{{ basic_ticket_stats.average_nbr_days_until_ticket_closed_last_60_days }}</strong>&nbsp;&nbsp;
                    ({% trans "Click" %} <strong><a href="{% url 'helpdesk:report_index' %}daysuntilticketclosedbymonth">here</a></strong>
                    {% trans "for detailed average by month." %})
                </td>
            </tr>
            </tbody>
        </table>

        <table class="table table-striped table-bordered table-hover">
            <thead>
            <tr>
                <th>{% trans "Queue" %}</th>
                <th>{% trans "New" %}</th>
                <th>{% trans "Open" %}</th>
                <th>{% trans "Resolved" %}</th>
                <th>{% trans "Closed" %}</th>
                <th>{% trans "Time spent" %}</th>
            </tr>
            </thead>
            <tbody>
            {% for queue in dash_tickets %}
                <tr>{% url 'helpdesk:list' as hdlist %}
                    <td><a href='{{ hdlist }}?queue={{ queue.queue }}&status=0&status=1&status=2'>{{ queue.name }}</a></td>
                    <td>{% if queue.new %}<a href='{{ hdlist }}?queue={{ queue.queue }}&status=0'>{% endif %}{{ queue.new }}{% if queue.new %}</a>{% endif %}</td>
                    <td>{% if queue.open %}<a href='{{ hdlist }}?queue={{ queue.queue }}&status=1&status=2'>{% endif %}{{ queue.open }}{% if queue.open %}</a>{% endif %}</td>
                    <td>{% if queue.resolved %}<a href='{{ hdlist }}?queue={{ queue.queue }}&status=3'>{% endif %}{{ queue.resolved }}{% if queue.resolved %}</a>{% endif %}</td>
                    <td>{% if queue.closed %}<a href='{{ hdlist }}?queue={{ queue.queue }}&status=4'>{% endif %}{{ queue.closed }}{% if queue.closed %}</a>{% endif %}</td>
                    <td>{{ queue.time_spent }}{% if queue.dedicated_time %} / {{ queue.dedicated_time }}{% endif %}</td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan='6'>{% trans "There are no unassigned tickets." %}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        {#            <!-- /.card-body -->#}
        {#        </div>#}
        {#        <!-- /.card -->#}
        {##}
        {#        <div class="card mb-3">#}
        {#            <div class="card-header">#}
        {#                <i class="fas fa-print"></i>#}
        {#                {% trans "Generate Report" %}#}
        {#            </div>#}
        {#            <div class="card-body">#}
        {#                <ul>#}
        {#                    <li>{% trans "Reports By User" %}#}
        {#                        <ul>#}
        {#                            <li><a href='userpriority/{% if saved_query %}?saved_query={{ saved_query }}{% endif %}'>{% trans "by Priority" %}</a></li>#}
        {#                            <li><a href='userqueue/{% if saved_query %}?saved_query={{ saved_query }}{% endif %}'>{% trans "by Queue" %}</a></li>#}
        {#                            <li><a href='userstatus/{% if saved_query %}?saved_query={{ saved_query }}{% endif %}'>{% trans "by Status" %}</a></li>#}
        {#                            <li><a href='usermonth/{% if saved_query %}?saved_query={{ saved_query }}{% endif %}'>{% trans "by Month" %}</a></li>#}
        {#                        </ul>#}
        {#                    </li>#}
        {#                    <li>{% trans "Reports By Queue" %}#}
        {#                        <ul>#}
        {#                            <li><a href='queuepriority/{% if saved_query %}?saved_query={{ saved_query }}{% endif %}'>{% trans "by Priority" %}</a></li>#}
        {#                            <li><a href='queuestatus/{% if saved_query %}?saved_query={{ saved_query }}{% endif %}'>{% trans "by Status" %}</a></li>#}
        {#                            <li><a href='queuemonth/{% if saved_query %}?saved_query={{ saved_query }}{% endif %}'>{% trans "by Month" %}</a></li>#}
        {#                            <li><a href='daysuntilticketclosedbymonth/{% if saved_query %}?saved_query={{ saved_query }}{% endif %}'>{% trans "Days until ticket closed by Month" %}</a></li>#}
        {#                        </ul>#}
        {#                    </li>#}
        {#                </ul>#}
        {#            </div>#}
        {#            <!-- /.card-body -->#}
        {#        </div>#}
        {#        <!-- /.card -->#}

    {% endif %}
{% endblock %}

django_project/web-app/templates/helpdesk/report_output.html
{% extends "helpdesk/report_base.html" %}
{% load i18n %}
{% load static %}

{% block header %}
    <i class="fas fa-chart-line"></i>&nbsp;
    {{ title }}
{% endblock %}

{% block sidebar_content %}
    <table class="table table-striped table-bordered table-hover">
        <thead>
        <tr>{% for h in headings %}
            <th>{% if forloop.first %}{{ h|title }}{% else %}{{ h }}{% endif %}</th>{% endfor %}
        </tr>
        </thead>
        <tbody>
        {% for d in data %}
            <tr class='row_{% cycle 'odd' 'even' %}'>
                {% for f in d %}
                    <td class='report'>{{ f }}</td>{% endfor %}
            </tr>
        {% endfor %}
        <tr>
            {% for f in total_data %}
                <td class='report'>{{ f }}</td>{% endfor %}
        </tr>
        </tbody>
    </table>
    </div>
    <!-- /.table-responsive -->
    <div class="flot-chart">
        <div class="flot-chart-content" id="chart-content"></div>
    </div>
    <!-- /.card -->
{% endblock %}


{% block extrascripts %}

<!-- Flot Charts JavaScript -->
<script src="/static/helpdesk/vendor/flot/excanvas.min.js"></script>
<script src="/static/helpdesk/vendor/flot/jquery.flot.js"></script>
<script src="/static/helpdesk/vendor/flot/jquery.flot.categories.js"></script>
<script src="/static/helpdesk/vendor/flot/jquery.flot.pie.js"></script>
<script src="/static/helpdesk/vendor/flot/jquery.flot.resize.js"></script>
<script src="/static/helpdesk/vendor/flot/jquery.flot.time.js"></script>
<script src="/static/helpdesk/vendor/flot-tooltip/jquery.flot.tooltip.min.js"></script>

<!-- Morris Charts JavaScript -->
{% if helpdesk_settings.HELPDESK_USE_CDN %}
    <script src="//cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/morris.js/0.5.1/morris.min.js"></script>
{% else %}
    <script src="{% static 'helpdesk/vendor/raphael/raphael.min.js' %}"></script>
    <script src="{% static 'helpdesk/vendor/morrisjs/morris.min.js' %}"></script>
{% endif %}

{% if charttype == "date" %}
<script type='text/javascript'>

    Morris.Line({
        element: 'chart-content',
        data: {% autoescape on %}{{ morrisjs_data|safe }}{% endautoescape %},
        xkey: 'x',
        ykeys: [{% for d in data %}{{ forloop.counter0 }}{% if not forloop.last %}, {% endif %}{% endfor %}],
        labels: [{% for n in series_names %}"{{ n }}"{% if not forloop.last %}, {% endif %}{% endfor %}],
        xLabels: "month"
    });

</script>
{% endif %}
{% if charttype == "bar" %}
<script type='text/javascript'>

    Morris.Bar({
        element: 'chart-content',
        data: {% autoescape on %}{{ morrisjs_data|safe }}{% endautoescape %},
        xkey: 'x',
        ykeys: [{% for d in data %}{{ forloop.counter0 }}{% if not forloop.last %}, {% endif %}{% endfor %}],
        labels: [{% for n in series_names %}"{{ n }}"{% if not forloop.last %}, {% endif %}{% endfor %}]
    });

</script>
{% endif %}


{% endblock %}

django_project/web-app/templates/helpdesk/ticket.html
{% extends "helpdesk/base.html" %}
{% load i18n bootstrap4form humanize webapp_tag %}
{% load static %}

{% block title %}
    {{ ticket.queue.slug }} #{{ ticket.id }} : {% trans "View Ticket Details" %}
{% endblock %}

{% block content %}
    {% get_user_by_username ticket.submitter_email as submitter %}
    {% get_feature_ticket ticket as feature_ticket %}
    {% get_recurring_ticket ticket as recurring_ticket %}
    <div class="ticket">
        {% if helpdesk_settings.HELPDESK_TRANSLATE_TICKET_COMMENTS %}
            <div id="google_translate_element"></div>
            <script src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>
        {% endif %}
        <div class="section title">
            {% string_to_css_class ticket.get_status as ticket_class %}
            <div class="row">
                <div class="ticket-title">#{{ ticket.id }} {{ ticket.title }}</div>
                <div class="col">
                    <div class="ticket-status {{ ticket_class }}">{{ ticket.get_status }}</div>
                </div>
            </div>
            <div class="subtitle">
                <b>{% blocktrans with ticket.queue as queue %}{{ queue }}{% endblocktrans %}</b> ●
                Opened
                {% if ticket.submitter_email %}
                    by <a href="{% url 'user-detail' ticket.submitter_email %}"><b>{{ submitter.full_str }}</b></a>
                {% endif %}
                <span title='{{ ticket.created|date:"DATETIME_FORMAT" }}'>{{ ticket.created|naturaltime }}</span>
            </div>
        </div>
        {% if feature_ticket %}
            {% include "helpdesk/ticket_features.html" %}
        {% endif %}
        <div class="content">
            <div class="row">
                <div class="col">
                    {% for followup in ticket.followup_set.all %}
                        {% include "helpdesk/ticket_comment.html" with followup=followup %}
                    {% endfor %}
                    {% if can_comment %}
                        {% include "helpdesk/ticket_comment_form.html" %}
                    {% endif %}
                </div>
                <div class="detail">
                    {% include "helpdesk/ticket_detail.html" %}
                </div>
            </div>
        </div>
        <br>
    </div>
{% endblock %}

django_project/web-app/templates/helpdesk/ticket_detail.html
{% load i18n humanize webapp_tag %}
<form id="detail-form" method='post' action='update/' enctype='multipart/form-data'>
    {% csrf_token %}
    {% if form %}
        <div class="section field">
            <div class="title">Title</div>
            <div class="field">
                {{ form.title }}
            </div>
        </div>
        <div class="section field">
            <div class="title">Description</div>
            <div class="field">
                {{ form.body }}
            </div>
        </div>
    {% endif %}
    <div class="section">
        <div class="title">Priority</div>
        {% string_to_css_class ticket.get_priority_display as priority_class %}
        <div class="value ticket-priority {{ priority_class }}">
            {{ ticket.get_priority_display }}
        </div>
        {% if form %}
            <div class="field">
                {{ form.priority }}
            </div>
        {% endif %}
    </div>
    <div class="section">
        <div class="section field">
            
        </div>
        <div class="title">
            Start date
        </div>
        <div class="value">
            {% if ticket.start_date %}
                {{ ticket.start_date|date:"DATETIME_FORMAT" }} {% if ticket.start_date %}({{ ticket.due_date|naturaltime }}){% endif %}
            {% else %}
                -
            {% endif %}
        </div>
        {% if form %}
            <div class="field">
                {{ form.start_date }}
            </div>
        {% endif %}
    </div>

    <div class="section">
        <div class="section field">
            
        </div>
        <div class="title">
            Link
        </div>
        <div class="value">
            <a href="{{ extra_fields.link }}" style="word-wrap: break-word;">{{ extra_fields.link }}</a>
        </div>
        {% if form %}
            <div class="field">
                {{ form.link }}
            </div>
        {% endif %}
    </div>

    <div class="section">
        <div class="title">
            Due date
        </div>
        <div class="value">
            {% if ticket.due_date %}
                {{ ticket.due_date|date:"DATETIME_FORMAT" }} {% if ticket.due_date %}({{ ticket.due_date|naturaltime }}){% endif %}
            {% else %}
                -
            {% endif %}
        </div>
        {% if form %}
            <div class="field">
                {{ form.due_date }}
            </div>
        {% endif %}
    </div>
    <div class="section">
        <div class="title">Operator</div>
        <div class="value">
            {% if ticket.assigned_to %}
                <a href="{% url 'user-detail' ticket.assigned_to.get_username %}">{{ ticket.assigned_to }}</a>
            {% else %}
                <i>Unassigned</i>
            {% endif %}
        </div>
        {% if form %}
            <div class="field">
                {{ form.assigned_to }}
            </div>
        {% endif %}
    </div>
    {% if can_recurring %}
        <div class="section">
            <div class="title">Recurring</div>
            <div class="value">
                {% if recurring_ticket and recurring_ticket.active %}
                    {{ recurring_ticket.recurring_type }}
                {% else %}
                    -
                {% endif %}
            </div>
            {% if form %}
                <div class="field">
                    {{ form.recurring_type }}
                </div>
            {% endif %}
            {% if recurring_ticket.active %}
                <br>
                <div class="title">Next Schedule</div>
                <div>
                    {{ recurring_ticket.next_date|date:"DATETIME_FORMAT" }} ({{ recurring_ticket.next_date|naturaltime }})
                </div>
            {% endif %}
        </div>
    {% endif %}
    <div class="section">
        <div class="title">Expected time to complete task</div>
        <div>
            <div class="value">
                {% if ticket.expected_time %}
                    {{ ticket.expected_time_formated }}
                {% else %}
                    -
                {% endif %}
            </div>
        </div>
        {% if form %}
            <div class="field">
                {{ form.expected_time }}
            </div>
        {% endif %}
    </div>
    <div class="section">
        <div class="title">Time spent</div>
        <div>
            {% if ticket.time_spent %}
                {{ ticket.time_spent_formated }}
            {% else %}
                00:00
            {% endif %}
        </div>
    </div>
    {% if form and can_delete_ticket %}
        <div class="detail-action">
            {% if form %}
                <button id="edit-button" class="btn btn-primary">Edit</button>
                <div id="submit-section" style="display: none">
                    <div>
                        <button id="cancel-button" class="btn btn-light">Cancel</button>
                    </div>
                    <div>
                        <button id="save-button" class="btn btn-primary">Save</button>
                    </div>
                </div>
            {% endif %}
            {% if can_delete_ticket %}
                <button id="delete-button" class="btn btn-danger">Delete</button>
            {% endif %}
        </div>
    {% endif %}
</form>

<script>
    $(document).ready(function () {
        const $field = $('#detail-form .field');
        const $value = $('#detail-form .value');
        const $editButton = $('#edit-button');
        const $submitSection = $('#submit-section');
        const $cancelButton = $('#cancel-button');
        const $saveButton = $('#save-button');
        const $deleteButton = $('#delete-button');
        $editButton.click(function () {
            $field.show();
            $value.hide();
            $editButton.hide();
            $deleteButton.hide();
            $submitSection.show();
            return false;
        });
        $cancelButton.click(function () {
            $field.hide();
            $value.show();
            $editButton.show();
            $submitSection.hide();
            $deleteButton.show();
            return false;
        });

        let assignedTo = '{{ ticket.assigned_to.id }}';
        $('#id_assigned_to').val(assignedTo);
        let recurringType = null;
        {% if recurring_ticket %}
            recurringType = '{{ recurring_ticket.recurring_type }}';
        {% endif%}
        $('#id_recurring_type').val(recurringType);
        const $startDateField = $('#id_start_date');
        if ($startDateField.val()) {
            $startDateField.val($startDateField.val().split(' ')[0])
        }
        $startDateField.datepicker({
            minDate: 0,
            dateFormat: 'yy-mm-dd'
        });
        const $dueDateField = $('#id_due_date');
        if ($dueDateField.val()) {
            $dueDateField.val($dueDateField.val().split(' ')[0])
        }
        $dueDateField.datepicker({
            minDate: 0,
            dateFormat: 'yy-mm-dd'
        });

        {% if can_delete_ticket %}
            $deleteButton.click(function () {
                if (confirm('Are you sure you want to delete this work order?')) {
                    $.ajax({
                        url: '{% url 'helpdesk:delete' ticket.id%}',
                        type: 'DELETE',
                        success: function (data) {
                            window.location = '{% url 'helpdesk:list'%}'
                        },
                        error: function (jqXhr, textStatus, errorMessage) {

                        },
                        beforeSend: beforeAjaxSend
                    });
                } else {

                }
                return false;
            })
        {% endif %}
    })
</script>

django_project/web-app/templates/helpdesk/ticket_features.html
{% load i18n %}
{% load static %}
<link href="{% static 'libs/leaflet/1.5.1/leaflet.css' %}" rel="stylesheet" type="text/css" media="screen, projection"/>
<script type="text/javascript" src="{% static 'libs/leaflet/1.5.1/leaflet.js' %}"></script>
<div id="map-wrapper">
    <div id="map">
        <div class="indicator">Loading</div>
    </div>
</div>


<script>
    function capitalize(string) {
        //check if it is already has upper case
        string = string.replaceAll('_', ' ')
        if (/[A-Z]/.test(string)) {
            return string;
        }
        return string.charAt(0).toUpperCase() + string.slice(1);
    }

    $(document).ready(function () {
        const $map = $('#map');
        const $mapWrapper = $('#map-wrapper');
        const $attributes = $('#map-attributes');
        $.get("{% url 'amlit_helpdesk:feature-ticket-detail' id=ticket.id %}", function (data) {
            $map.html('')
            $map.css("width", "100%");
            $map.css("height", "100%");
            $mapWrapper.css("height", "300px");

            {# setup map #}
            var osm = L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
                maxZoom: 19,
                attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
            });

            var markerStyle = {
                radius: 5,
                weight: 2,
                opacity: 1,
            };
            var layer = L.geoJSON(data.features, {
                onEachFeature: function (feature, layer) {
                    const keys = Object.keys(feature.properties).sort();
                    let rows = []
                    $.each(keys, function (value, key) {
                        value = feature.properties[key];
                        rows.push(`
                           <tr>
                              <td>${capitalize(key)}</td>
                              <td>${value ? value : '-'}</td>
                           </tr>
                       `)
                    });
                    layer.bindPopup(`<table>${rows.join('')}</table>`);
                },
                pointToLayer: function (feature, latlng) {
                    return L.circleMarker(latlng, markerStyle);
                }
            });
            const map = L.map('map', {
                center: [39.73, -104.99],
                zoom: 10,
                layers: [osm, layer]
            });
            map.fitBounds(layer.getBounds());
            $attributes.show();
        }).fail(function () {
            $map.html('<div class="indicator">Aset not found</div>')
        });

    })
    ;
</script>