django_project/core/urls.py
# coding=utf-8
"""Project level url handler."""
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

admin.autodiscover()

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^auth/', include('django.contrib.auth.urls')),
    url(r'^work-order/', include('amlit_helpdesk.urls')),
    url(r'^work-order/', include('amlit_helpdesk.urls_helpdesk')),
    url(r'^', include('civitas.urls')),
    url(r'^', include('amlit.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_project/amlit/models/user.py
__author__ = 'Irwan Fathurrahman <meomancer@gmail.com>'
__date__ = '18/03/21'

from django.conf import settings
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.db import models
from django.utils.translation import ugettext_lazy as _
from phone_field import PhoneField
from core.models.term import TermModel


class UserTitle(TermModel):
    """
    Contains title of an user specification
    """
    name = models.CharField(
        _('title'), max_length=512, unique=True)

    def __str__(self):
        return self.name


class UserManager(BaseUserManager):
    """Define a model manager for User model with no username field."""

    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """Create and save a User with the given email and password."""
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        """Create and save a regular User with the given email and password."""
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        """Create and save a SuperUser with the given email and password."""
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class User(AbstractUser):
    """
    Users within the Django authentication system are represented by this model.

    Username and password are required. Other fields are optional.
    We make username as email format
    """

    username = None
    email = models.EmailField(
        _('email address'), unique=True
    )

    title = models.ForeignKey(
        UserTitle,
        null=True, blank=True,
        on_delete=models.SET_NULL,
        verbose_name=_('title')
    )
    phone = PhoneField(
        blank=True, help_text=_('Contact phone number')
    )
    avatar = models.ImageField(
        upload_to="avatar", blank=True
    )

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = UserManager()

    def __str__(self):
        if self.first_name or self.last_name:
            return self.get_username() + ' ({})'.format(' '.join([self.first_name, self.last_name]))
        else:
            return self.get_username()

    @property
    def organisations_as_admin(self):
        """ Return organisation that has admin role or owner """
        from amlit.models.organisation import Organisation
        return Organisation.by_user.admin_role(self)

    @property
    def organisations(self):
        """ Return organisations that user have access to """
        from amlit.models.organisation import Organisation
        return Organisation.by_user.all_role(self)

    @property
    def communities(self):
        """ Return communities that user have access to  """
        from civitas.models.community import Community
        queryset = Community.objects.all()
        if not self.is_staff:
            cummonity_codes = list(self.organisations.values_list(
                'community_code', flat=True))
            queryset = queryset.filter(code__in=cummonity_codes)
        return queryset

    @property
    def avatar_url(self) -> str:
        """ return avatar url """
        if self.avatar:
            return self.avatar.url
        return settings.STATIC_URL + 'img/no-profile.png'


class UserByString:
    user = None
    username = None

    def __init__(self, username):
        self.username = username
        try:
            self.user = User.objects.get(**{'{}'.format(User.USERNAME_FIELD): username})
        except User.DoesNotExist:
            pass

    def __str__(self):
        if self.user:
            return self.user.__str__()
        return self.username

    def full_str(self):
        """ return __str__ """
        return self.__str__()

    @property
    def avatar_url(self) -> str:
        """ return avatar url """
        if self.user:
            return self.user.avatar_url
        return settings.STATIC_URL + 'img/no-profile.png'

django_project/core/models/term.py
__author__ = 'Irwan Fathurrahman <meomancer@gmail.com>'
__date__ = '18/03/21'

from django.contrib.gis.db import models
from django.utils.translation import ugettext_lazy as _


class TermModel(models.Model):
    """ Abstract model for Term """

    name = models.CharField(
        _('name'), max_length=512, unique=True)
    description = models.TextField(
        _('description'), null=True, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        abstract = True
        ordering = ('name',)

django_project/amlit/forms/organisation.py
__author__ = 'Irwan Fathurrahman <meomancer@gmail.com>'
__date__ = '18/03/21'

import json
from django import forms
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
from amlit.models.organisation import (
    Organisation, UserOrganisation, UserOrganisationInvitation, UserRole
)
from civitas.models.community import Community

User = get_user_model()


class OrganisationForm(forms.ModelForm):
    name = forms.CharField(
        label=_('Organisation name'),
        required=False,
        help_text='Keep this empty will fill the same name with community.',
    )
    community_code = forms.ModelChoiceField(
        Community.objects.all(),
        label=_('Community')
    )

    class Meta:
        model = Organisation
        fields = (
            'name', 'description', 'owner', 'community_code')

    def __init__(self, *args, **kwargs):
        super(OrganisationForm, self).__init__(*args, **kwargs)
        codes = list(Organisation.objects.values_list('community_code', flat=True))
        if self.instance.id:
            codes.remove(self.instance.community_code)
            try:
                community = Community.objects.get(
                    code=self.instance.community_code)
                self.fields['community_code'].initial = community
                self.initial['community_code'] = community
            except Community.DoesNotExist:
                pass
        self.fields['community_code'].choices = [(c.id, c.__str__()) for c in Community.objects.exclude(
            code__in=codes
        ).order_by('name')]

    def clean(self):
        cleaned_data = self.cleaned_data
        community = cleaned_data.get('community_code', None)
        if community:
            cleaned_data['community_code'] = community.code

        name = self.cleaned_data['name']
        try:
            if not name:
                if not community:
                    raise ValidationError('Community is required')
                name = community.name
            Organisation.objects.exclude(pk=self.instance.pk).get(name=name)
            raise ValidationError('This organisation name already exist')
        except Organisation.DoesNotExist:
            pass
        self.cleaned_data['name'] = name
        return cleaned_data


class OrganisationCreateForm(OrganisationForm):
    class Meta:
        model = Organisation
        fields = (
            'community_code', 'name', 'description')

    def __init__(self, *args, **kwargs):
        super(OrganisationCreateForm, self).__init__(*args, **kwargs)


class UserOrganisationForm(forms.ModelForm):
    class Meta:
        model = UserOrganisation
        fields = ('id', 'user', 'organisation', 'role')

    def __init__(self, *args, **kwargs):
        super(UserOrganisationForm, self).__init__(*args, **kwargs)
        self.fields['role'].choices = [
            (c.id, c.name) for c in UserRole.objects.all()]
        try:
            instance = kwargs['instance']
            initial = kwargs['initial']
            self.fields['user'].widget.attrs['disabled'] = True
            if instance.organisation.owner.id == initial['user']:
                self.fields['role'].widget.attrs['disabled'] = True

        except KeyError:
            pass


class UserOrganisationInvitationForm(forms.ModelForm):
    class Meta:
        model = UserOrganisationInvitation
        fields = ('email', 'role')

    def __init__(self, *args, **kwargs):
        super(UserOrganisationInvitationForm, self).__init__(*args, **kwargs)
        self.fields['role'].choices = [
            (c.id, c.name) for c in UserRole.objects.all()]
        self.fields['email'].widget.attrs['disabled'] = True

django_project/amlit/views/organisations.py
import json

from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.forms.models import model_to_dict
from django.http import JsonResponse
from django.shortcuts import reverse, get_object_or_404
from django.views.generic import DetailView, ListView

from amlit.forms.organisation import (
    UserOrganisationForm,
    UserOrganisationInvitationForm
)
from amlit.models.organisation import Organisation
from amlit_helpdesk.forms.scheduled_ticket import ScheduledTicketForm


class OrganisationListView(LoginRequiredMixin, ListView):
    """ Showing list of organisation of an user
    """
    template_name = 'pages/organisations/list.html'
    model = Organisation

    def get_queryset(self):
        return Organisation.by_user.all_role(self.request.user)


class OrganisationDetailView(LoginRequiredMixin, DetailView):
    """ Showing Organisation detail
    """
    model = Organisation
    template_name = 'pages/organisations/detail.html'

    def get_success_url(self):
        return reverse('organisation_list')

    def get_context_data(self, **kwargs):
        context = super(OrganisationDetailView, self).get_context_data(
            **kwargs)
        users = {
            'form': UserOrganisationForm(),
            'data': [],
            'pendings': []
        }
        for user_org in self.object.userorganisation_set.filter(
                user=self.object.owner):
            users['data'].append(
                UserOrganisationForm(
                    initial=model_to_dict(user_org),
                    instance=user_org)
            )
        for user_org in self.object.userorganisation_set.exclude(
                user=self.object.owner).order_by('user__email'):
            users['data'].append(
                UserOrganisationForm(
                    initial=model_to_dict(user_org),
                    instance=user_org)
            )
        for user_org in self.object.userorganisationinvitation_set.all().order_by(
                'email'):
            users['pendings'].append(
                UserOrganisationInvitationForm(
                    initial=model_to_dict(user_org),
                    instance=user_org)
            )
        context['users'] = users
        context['users_count'] = len(users['data'])
        
        context['scheduled_form'] = ScheduledTicketForm(
            assigned_to_choices=self.object.operators)
        return context


class SubscriptionView(LoginRequiredMixin, DetailView):
    """ Subscription view for an organisation
    """
    template_name = "pages/organisations/subscription.html"
    model = Organisation

    def get_context_data(self, **kwargs):
        context = super(SubscriptionView, self).get_context_data(**kwargs)
        if not self.object.is_owner(self.request.user):
            raise PermissionDenied('You do not have permission.')

        context['url_submit'] = reverse(
            'organisation_subscription', args=[self.object.pk]
        )
        return context

    def post(self, request, *args, **kwargs):
        organisation = self.get_object()
        data = json.loads(request.body)
        try:
            organisation.subscribe(request.user, data)
            return JsonResponse({'Result': 'OK'})

        except Exception as e:
            return JsonResponse({'error': (e.args[0])}, status=403)


class SubscriptionChangeView(LoginRequiredMixin, DetailView):
    """ Subscription change view for an organisation
    """
    template_name = "pages/organisations/subscription-change.html"
    model = Organisation

    def get_context_data(self, **kwargs):
        context = super(SubscriptionChangeView, self).get_context_data(
            **kwargs)
        if not self.object.is_owner(self.request.user):
            raise PermissionDenied('You do not have permission.')

        return context

    def post(self, request, *args, **kwargs):
        organisation = self.get_object()
        data = json.loads(request.body)
        plan = get_object_or_404(Plan, id=data.get('plan_id', 0))
        organisation.change_plan(plan)
        return JsonResponse({'Result': 'OK'})


class SubscriptionCompleteView(LoginRequiredMixin, DetailView):
    """ Page when subscription is completed
    """
    template_name = "pages/organisations/complete.html"
    model = Organisation


class SignupCompleteView(LoginRequiredMixin, DetailView):
    """ Page when signup is completed
    """
    template_name = "registration/complete.html"
    model = Organisation

django_project/web-app/templates/pages/organisations/widgets/manage_access.html
<style>
    #manage-access input {
        width: auto;
    }

    #manage-access .col > span {
        margin-top: 10px;
        display: inline-block;
    }

    #manage-access .invitation .col > span {
        margin-top: 0;
    }
</style>
<div id="manage-access" class="sidebar-content">
    <h5>User access {% if ENABLE_SUBSCRIPTION %}({{ object.users_count }}/<span class="max-user"></span>){% endif %}
        <button id="invite-button" class="pull-right red-button" data-toggle="modal" data-target="#invite-user">Invite user</button>
    </h5>
    {% if ENABLE_SUBSCRIPTION %}
        <div class="info">Your organization is using {{ object.users_count }}of <span class="max-user"></span> available users. <br>To increase or decrease the number of available users, please change your subscription.
            {% if object.subscription.is_status_current %}
                {% if object.subscription.cancel_at_period_end %}
                    <br>
                    <br>
                    <div style="color: red">
                        Your organization still be able to assign user up to <span class="max-user"></span> until {{ object.subscription.current_period_end }}
                    </div>
                {% endif %}
            {% endif %}
        </div>
    {% endif %}
    <br>
    {% for data in users.data %}
        <div class="row user-access">
            <div class="col">
                <span>{{ data.instance.user }}</span>
            </div>
            <div class="role" style="width: 300px" data-url="{% url "organisation-user-access" pk=data.instance.pk %}">
                <b>Role :</b> {{ data.role }}
            </div>
            <div class="delete-column">
                {% if object.owner != data.instance.user and data.instance.user != user %}
                    <div class="remove" data-url='{% url "organisation-user-access" pk=data.instance.pk %}'>
                        <i class="fa fa-trash" aria-hidden="true"></i>
                    </div>
                {% endif %}
            </div>
        </div>
    {% endfor %}
    {% for data in users.pendings %}
        <div class="row user-access invitation">
            <div class="col">
                <span>
                    <b>( Pending )</b>
                    {{ data.instance.email }}
                    <div>
                        Click <a href="{% url "user-organisation-invitation-page" uuid=data.instance.uuid %}">here</a> to see the invitation.
                    </div>
                </span>
            </div>
            <div class="role" style="width: 300px" data-url='{% url "user-organisation-invitation-detail" pk=data.instance.pk %}'>
                <b>Role :</b> {{ data.role }}
            </div>
            <div class="delete-column">
                <div class="remove" data-url='{% url "user-organisation-invitation-detail" pk=data.instance.pk %}'>
                    <i class="fa fa-trash" aria-hidden="true"></i>
                </div>
            </div>
        </div>
    {% endfor %}
</div>

<!-- Modal -->
<div id="invite-user" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close pull-right" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Invite a user</h4>
            </div>
            <div class="modal-body">
                <form method="POST" action="{% url 'organisation_invite_user' pk=object.pk %}">
                    {% csrf_token %}
                    <label>Email </label>
                    <input id="user-input" type="email" placeholder="Email of user" name="email">
                    <br>
                    <br>
                    <label>Role </label>
                    {{ users.form.role }}
                    <br>
                    <br>
                    <button type="submit" class="save btn btn-primary">Invite</button>
                </form>
            </div>
        </div>

    </div>
</div>
<script>
    $(document).ready(function () {
        $('#manage-access .delete-column .remove').click(function () {
            $.ajax({
                url: $(this).data('url'),
                type: 'DELETE',
                beforeSend: beforeAjaxSend,
                success: function () {
                    location.reload();
                }
            });
        })
        $('#manage-access .role select').change(function () {
            $.ajax({
                url: $(this).closest('.role').data('url'),
                type: 'PUT',
                data: {
                    role: $(this).val()
                },
                beforeSend: beforeAjaxSend,
                success: function () {
                    location.reload();
                }
            });
        })
    })
</script>

django_project/web-app/templates/pages/organisations/widgets/work_order_scheduler.html
{% load static %}
{% load amlit_organisation %}
<style>

    #scheduler-table {
        width: 100%;
        font-size: 14px;
    }

    #scheduler-table th,
    #scheduler-table td {
        border: 1px solid #ddd;
        padding: 8px 15px;
        vertical-align: top;
    }

    #scheduler-table td {
        opacity: 0.5;
    }

    #scheduler-table tr.active td {
        opacity: 1 !important;
    }

    #scheduler-table h2 {
        position: relative;
    }

    #scheduler-table h2 a {
        position: absolute;
        right: 0;
    }

    #scheduler-table .action {
        opacity: 1 !important;
    }

    #scheduler-table .action button {
        padding: 5px 10px;
    }

    #scheduler-table .ticket-link {
        font-size: 16px;
    }

    #scheduler-table .title {
        background: #eee;
        color: var(--primary-color);
        font-weight: 700;
        opacity: 1;
        cursor: pointer;
    }

    #scheduler-template-button {
        font-size: 14px;
        padding: 5px 10px;
    }

    #work-order-scheduler-table {
        width: 100%;
        overflow-x: auto;
    }

    #scheduler-table .btn {
        width: 90px;
    }

</style>
<div id="work-order-scheduler" class="sidebar-content">
    {% if site_preferences.recurred_queues.first  %}
        <button class="btn btn-success template_form_button"
                style="margin-top: 5px"
                data-form-title="Create new schedule"
                data-form-url="{% url "organisation_schedule_create" object.id %}">Create New Schedule
        </button>
        <button id="scheduler-template-button" class="red-button pull-right" data-toggle="modal" data-target="#scheduler-template">
            See Schedule Templates
        </button>
        <br>
        <br>
        <div id="work-order-scheduler-table">
            <table id="scheduler-table">
                <tr>
                    <th>Status</th>
                    <th>Asset Type</th>
                    <th>Schedule</th>
                    <th>Activity Summary</th>
                    <th>Activity Description</th>
                    <th>Assign to</th>
                    <th>Ticket link</th>
                    <th>Actions</th>
                </tr>
                {% for scheduler_data in object.scheduler_data %}
                    <tr
                            {% for key, value in scheduler_data.items %}
                                data-{{ key }}="{{ value }}"
                            {% endfor %}
                                class="{% if scheduler_data.active %}active{% endif %}"
                    >
                        <td>{% if scheduler_data.active %}Active{% else %}Inactive{% endif %}</td>
                        <td>{{ scheduler_data.feature_type_combination_str }}</td>
                        <td>{{ scheduler_data.recurring_type }}</td>
                        <td>{{ scheduler_data.title }}</td>
                        <td>{{ scheduler_data.description }}</td>
                        <td>{% if scheduler_data.operator %}{{ scheduler_data.operator }}{% endif %}</td>
                        <td class="ticket-link">{% if scheduler_data.ticket_link %}<a href="{{ scheduler_data.ticket_link }}"><i class="fa fa-ticket" aria-hidden="true"></i></a>{% endif %}</td>
                        <td class="action">
                            {% if scheduler_data.ticket_link %}
                                <div>
                                    {% if scheduler_data.active %}
                                        <form action="{% url "organisation_schedule_inactivate" object.id scheduler_data.id %}" method="POST">
                                            {% csrf_token %}
                                            <button class="btn btn-danger">Inactivate</button>
                                        </form>
                                    {% else %}
                                        <form action="{% url "organisation_schedule_activate" object.id scheduler_data.id %}" method="POST">
                                            {% csrf_token %}
                                            <button class="btn btn-success">Activate</button>
                                        </form>
                                    {% endif %}
                                </div>
                                <div>
                                    <button class="btn btn-secondary template_form_button"
                                            style="margin-top: 5px"
                                            data-form-title="Edit the schedule"
                                            data-form-url="{% url "organisation_schedule_edit" object.id scheduler_data.id %}">Edit
                                    </button>
                                </div>
                            {% else %}
                                <div>
                                    <button class="btn btn-success template_form_button"
                                            style="margin-top: 5px"
                                            data-form-title="Edit and activate the schedule"
                                            data-form-url="{% url "organisation_schedule_edit" object.id scheduler_data.id %}">Edit & Activate
                                    </button>
                                </div>
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    {% else %}
        <div>
            There is no queue for Work Order in Schedule. Please contact Admin to add it.
        </div>
    {% endif %}
</div>
{% include "pages/organisations/widgets/work_order_scheduler_templates.html" %}
{% include "pages/organisations/widgets/work_order_scheduler_form.html" %}
<script type="text/javascript" src="{% static 'js/forms/widget/recurring_type.js' %}"></script>
<script type="text/javascript" src="{% static 'js/forms/widget/expected_time.js' %}"></script>
<script>
    $(document).ready(function () {
        $('.template_form_button').click(function () {
            const $row = $(this).closest('tr');
            const formTitle = $(this).data('form-title');
            const formUrl = $(this).data('form-url');

            $('#id_feature_type_combination').val($row.data('feature_type_combination_id'));
            $('#id_title').val($row.data('title'));
            $('#id_description').val($row.data('description'));
            $('#id_assigned_to').val($row.data('operator_id'));
            assignNewRecurring($row.data('recurring_type'));
            $('#scheduler-form form').attr('action', formUrl);
            $('#scheduler-form .modal-title').html(formTitle);
            $('#scheduler-form').modal('toggle');
            $('#scheduler-template').modal('hide');
        });
        $('.default-recurrence').remove();
    });
</script>

django_project/web-app/templates/pages/organisations/widgets/work_order_scheduler_form.html
{% load i18n static %}
<div class="modal fade" tabindex="-1" role="dialog" id="scheduler-form">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Modal title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true"></span>
                </button>
            </div>
            <form method='post' enctype='multipart/form-data'>
                {% csrf_token %}
                <div class="modal-body">
                    {% for field in scheduled_form %}
                        <div class="form-group">
                            <label for='id_{{ field.name }}'>
                                {{ field.label }}
                                {% if not field.field.required %}
                                    ({% trans "Optional" %})
                                {% endif %}
                            </label>
                            {{ field }}
                            {% if field.errors %}
                                <small class='error'>{{ field.errors }}</small>
                            {% endif %}
                            {% if field.help_text %}
                                <small class='form_help_text help-block'>{% trans field.help_text %}</small>
                            {% endif %}
                        </div>
                    {% endfor %}
                </div>
                <div class="modal-footer row">
                    <button type="submit" class="btn btn-primary btn-lg btn-block col" style="margin-top: 0">
                        {% trans "Save" %}
                    </button>
                    <button type="button" class="btn btn-secondary btn-lg btn-block col" style="margin-top: 0" data-dismiss="modal">
                        {% trans "Close" %}
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

django_project/web-app/templates/pages/organisations/widgets/work_order_scheduler_templates.html
{% load i18n static %}
<div class="modal fade" tabindex="-1" role="dialog" id="scheduler-template">
    <div class="modal-dialog" role="document" style="max-width: 80%;">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Work order schedule templates</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true"></span>
                </button>
            </div>
            {% csrf_token %}
            <div class="modal-body">
                <table id="template-table">
                    <tr>
                        <th>Asset Type</th>
                        <th>Schedule</th>
                        <th>Activity Summary</th>
                        <th>Activity Description</th>
                        <th>Actions</th>
                    </tr>
                    {% for scheduler_data in object.scheduler_templates %}
                        <tr
                                {% for key, value in scheduler_data.items %}
                                    data-{{ key }}="{{ value }}"
                                {% endfor %}
                        >
                            <td>{{ scheduler_data.feature_type_combination_str }}</td>
                            <td>{{ scheduler_data.recurring_type }}</td>
                            <td>{{ scheduler_data.title }}</td>
                            <td>{{ scheduler_data.description }}</td>
                            <td class="action">
                                <div>
                                    <button
                                            id="create-form" class="red-button template_form_button"
                                            data-form-title="Create new schedule from template"
                                            data-form-url="{% url "organisation_schedule_create" object.id %}"
                                    >
                                        Edit & Activate
                                    </button>
                                </div>
                            </td>
                        </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
</div>